#!/usr/bin/env sh

# abort on errors
set -e

# build
npm run build

# navigate into the build output directory
cd dist

# если вы деплоите на кастомный домен
# echo 'www.example.com' > CNAME

git init
git add -A
git commit -m 'deploy'

# если вы деплоите на https://<USERNAME>.github.io
# git push -f git@github.com:Clarus2137/Clarus2137.github.io.git master

# если вы деплоите на https://Clarus2137.github.io/<REPO>
git push -f git@github.com:dream-agency/Clarus2137.git master:gh-pages

cd -
          # Используйте токен для аутентификации в URL-адресе репозитория
          git push -f https://$GH_TOKEN@github.com/Clarus2137/dream-agency.git gh-pages
        env:
          GH_TOKEN: ${{ secrets.UNIQE_TOKEN }}
