name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          git config --global user.email "your email"
          git config --global user.name "your github username"

          git checkout --orphan gh-pages
          git rm -rf .
          git add -f dist
          git commit -m "Deploy to gh-pages"

          # Используйте токен для аутентификации в URL-адресе репозитория
          git push -f https://$GH_TOKEN@github.com/Clarus2137/dream-agency.git gh-pages
        env:
          GH_TOKEN: ${{ secrets.UNIQE_TOKEN }}
